/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { AxiosRequestConfig } from "axios";
import request from "@/core/utils/request";
import { InlineResponse20024 } from "../models";

/**
 * CommonApi -
 * @export
 */
export const CommonApi = {
  /**
   *
   * @summary 上传图片接口
   * @param {any} file
   * @param {string} imageType campaign/nft/avatar/pow/text
   * @param {*} [options] Override http request option.
   * @memberof CommonApi
   */
  async v1UploadImagePost(
    file: any,
    imageType: string,
    options?: AxiosRequestConfig
  ) {
    const formData = new FormData();
    formData.append("file", file as any);
    formData.append("imageType", imageType as any);
    const { result } = await request<InlineResponse20024>({
      url: "/v1/uploadImage",
      method: "POST",
      data: formData,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },
};
