/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { AxiosRequestConfig } from "axios";
import request from "@/core/utils/request";
import {
  InlineObject22,
  InlineResponse20023,
  InlineResponse20041,
} from "../models";

/**
 * ConfigApi -
 * @export
 */
export const ConfigApi = {
  /**
   *
   * @summary 获取campaign Chain 信息
   * @param {InlineObject22} [inlineObject22]
   * @param {*} [options] Override http request option.
   * @memberof ConfigApi
   */
  async v1GetCampaignChainInfoPost(
    inlineObject22?: InlineObject22,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse20023>({
      url: "/v1/getCampaignChainInfo",
      method: "POST",
      data: inlineObject22,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   *
   * @summary 获取Chain 信息
   * @param {string} [body]
   * @param {*} [options] Override http request option.
   * @memberof ConfigApi
   */
  async v1GetChainInfoPost(body?: string, options?: AxiosRequestConfig) {
    const { result } = await request<InlineResponse20023>({
      url: "/v1/getChainInfo",
      method: "POST",
      data: body,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   *
   * @summary 获取上传文件的模板url
   * @param {string} [body]
   * @param {*} [options] Override http request option.
   * @memberof ConfigApi
   */
  async v1GetUploadFileTemplateUrlPost(
    body?: string,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse20041>({
      url: "/v1/getUploadFileTemplateUrl",
      method: "POST",
      data: body,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },
};
