/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { AxiosRequestConfig } from "axios";
import request from "@/core/utils/request";
import {
  AuthRequest,
  InlineObject1,
  InlineObject3,
  InlineResponse2001,
  InlineResponse2007,
  TaskOnResponse,
} from "../models";

/**
 * LoginApi -
 * @export
 */
export const LoginApi = {
  /**
   * 注销登录，之前获得的登录token将会被注销
   * @summary 注销登录
   * @param {*} [options] Override http request option.
   * @memberof LoginApi
   */
  async v1LogoutPost(options?: AxiosRequestConfig) {
    const { result } = await request<TaskOnResponse>({
      url: "/v1/logout",
      method: "POST",

      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   *
   * @summary 请求challenge
   * @param {AuthRequest} [authRequest]
   * @param {*} [options] Override http request option.
   * @memberof LoginApi
   */
  async v1RequestChallengePost(
    authRequest?: AuthRequest,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse2007>({
      url: "/v1/requestChallenge",
      method: "POST",
      data: authRequest,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   * SNS 登录，如Twitter登录等
   * @summary SNS 登录接口
   * @param {InlineObject3} [inlineObject3]
   * @param {*} [options] Override http request option.
   * @memberof LoginApi
   */
  async v1SnsLoginPost(
    inlineObject3?: InlineObject3,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse2001>({
      url: "/v1/snsLogin",
      method: "POST",
      data: inlineObject3,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   * 使用前端签名的challenge 登录
   * @summary 地址登录
   * @param {InlineObject1} [inlineObject1]
   * @param {*} [options] Override http request option.
   * @memberof LoginApi
   */
  async v1SubmitChallengePost(
    inlineObject1?: InlineObject1,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse2001>({
      url: "/v1/submitChallenge",
      method: "POST",
      data: inlineObject1,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },
};
