/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { AxiosRequestConfig } from "axios";
import request from "@/core/utils/request";
import {
  AddFailedLogParams,
  InlineObject20,
  InlineResponse20039,
  InlineResponse20046,
  InlineResponse20052,
  TraceFromSourceParams,
} from "../models";

/**
 * OtherApi -
 * @export
 */
export const OtherApi = {
  /**
   * 需要用户登录
   * @summary 上报错误日志
   * @param {AddFailedLogParams} [addFailedLogParams]
   * @param {*} [options] Override http request option.
   * @memberof OtherApi
   */
  async v1AddFailedLogPost(
    addFailedLogParams?: AddFailedLogParams,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse20052>({
      url: "/v1/addFailedLog",
      method: "POST",
      data: addFailedLogParams,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   *
   * @summary 统计页面访问量
   * @param {TraceFromSourceParams} [traceFromSourceParams]
   * @param {*} [options] Override http request option.
   * @memberof OtherApi
   */
  async v1TraceFromSourcePost(
    traceFromSourceParams?: TraceFromSourceParams,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse20039>({
      url: "/v1/traceFromSource",
      method: "POST",
      data: traceFromSourceParams,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   *
   * @summary 检查web链接是否可以访问
   * @param {InlineObject20} [inlineObject20]
   * @param {*} [options] Override http request option.
   * @memberof OtherApi
   */
  async v1WebLinkCheckPost(
    inlineObject20?: InlineObject20,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse20046>({
      url: "/v1/webLinkCheck",
      method: "POST",
      data: inlineObject20,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },
};
