/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { AxiosRequestConfig } from "axios";
import request from "@/core/utils/request";
import {
  GetRewardTokenAmountParams,
  InlineObject6,
  InlineResponse20010,
  InlineResponse20011,
  InlineResponse20013,
  InlineResponse20018,
} from "../models";

/**
 * RewardApi -
 * @export
 */
export const RewardApi = {
  /**
   *
   * @summary 查询Campaing奖励发放信息
   * @param {number} [body]
   * @param {*} [options] Override http request option.
   * @memberof RewardApi
   */
  async v1GetCampaignRewardDistributionPost(
    body?: number,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse20018>({
      url: "/v1/getCampaignRewardDistribution",
      method: "POST",
      data: body,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   *
   * @summary 查询用户取得的NFT数量
   * @param {*} [options] Override http request option.
   * @memberof RewardApi
   */
  async v1GetUserRewardNFTAmountPost(options?: AxiosRequestConfig) {
    const { result } = await request<InlineResponse20011>({
      url: "/v1/getUserRewardNFTAmount",
      method: "POST",

      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   *
   * @summary 查询用户RewardToken的总数
   * @param {GetRewardTokenAmountParams} [getRewardTokenAmountParams]
   * @param {*} [options] Override http request option.
   * @memberof RewardApi
   */
  async v1GetUserRewardTokensAmountPost(
    getRewardTokenAmountParams?: GetRewardTokenAmountParams,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse20010>({
      url: "/v1/getUserRewardTokensAmount",
      method: "POST",
      data: getRewardTokenAmountParams,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },

  /**
   * 按reward type 查询所有的reward信息
   * @summary 查询用户奖励
   * @param {InlineObject6} [inlineObject6]
   * @param {*} [options] Override http request option.
   * @memberof RewardApi
   */
  async v1GetUserRewardsPost(
    inlineObject6?: InlineObject6,
    options?: AxiosRequestConfig
  ) {
    const { result } = await request<InlineResponse20013>({
      url: "/v1/getUserRewards",
      method: "POST",
      data: inlineObject6,
      ...options,
    });
    if (typeof result === "undefined") {
      throw new Error("unexpected: result should exist when no error");
    }
    return result;
  },
};
