/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { NftType } from "./nft-type";

/**
 *
 * @export
 * @interface AddNftCollectionMetadataParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface AddNftCollectionMetadataParams {
  /**
   *
   * @type {string}
   * @memberof AddNftCollectionMetadataParams
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof AddNftCollectionMetadataParams
   */
  token_address: string;
  /**
   *
   * @type {string}
   * @memberof AddNftCollectionMetadataParams
   */
  symbol: string;
  /**
   *
   * @type {NftType}
   * @memberof AddNftCollectionMetadataParams
   */
  nft_type: NftType;
  /**
   *
   * @type {string}
   * @memberof AddNftCollectionMetadataParams
   */
  chain: string;
}
