/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface AuthChallengeServer
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface AuthChallengeServer {
  /**
   *
   * @type {string}
   * @memberof AuthChallengeServer
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof AuthChallengeServer
   */
  icon: string;
  /**
   *
   * @type {string}
   * @memberof AuthChallengeServer
   */
  url: string;
  /**
   *
   * @type {string}
   * @memberof AuthChallengeServer
   */
  did: string;
  /**
   *
   * @type {string}
   * @memberof AuthChallengeServer
   */
  verificationMethod: string;
}
