/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface AuthChallengeVCFilters
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface AuthChallengeVCFilters {
  /**
   *
   * @type {string}
   * @memberof AuthChallengeVCFilters
   */
  type: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AuthChallengeVCFilters
   */
  trustRoot: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof AuthChallengeVCFilters
   */
  required: boolean;
  /**
   * 非必须
   * @type {Array<string>}
   * @memberof AuthChallengeVCFilters
   */
  express: Array<string>;
}
