/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { AuthChallengeServer } from "./auth-challenge-server";
import { AuthChallengeVCFilters } from "./auth-challenge-vcfilters";

/**
 *
 * @export
 * @interface AuthChallenge
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface AuthChallenge {
  /**
   *
   * @type {string}
   * @memberof AuthChallenge
   */
  ver: string;
  /**
   *
   * @type {string}
   * @memberof AuthChallenge
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof AuthChallenge
   */
  nonce: string;
  /**
   *
   * @type {AuthChallengeServer}
   * @memberof AuthChallenge
   */
  server: AuthChallengeServer;
  /**
   *
   * @type {Array<string>}
   * @memberof AuthChallenge
   */
  chain: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof AuthChallenge
   */
  alg: Array<string>;
  /**
   * 当前为空数组
   * @type {Array<AuthChallengeVCFilters>}
   * @memberof AuthChallenge
   */
  VCFilters: Array<AuthChallengeVCFilters>;
}
