/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { ChainType } from "./chain-type";

/**
 *
 * @export
 * @interface BindAddressParamsData
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface BindAddressParamsData {
  /**
   * 固定为taskon
   * @type {string}
   * @memberof BindAddressParamsData
   */
  server_name: string;
  /**
   * 以秒为单位的时间戳
   * @type {number}
   * @memberof BindAddressParamsData
   */
  timestamp: number;
  /**
   * 待绑定的地址
   * @type {string}
   * @memberof BindAddressParamsData
   */
  address: string;
  /**
   * 绑定地址的用户id
   * @type {number}
   * @memberof BindAddressParamsData
   */
  user_id: number;
  /**
   *
   * @type {ChainType}
   * @memberof BindAddressParamsData
   */
  chain_type: ChainType;
  /**
   * 公钥hex
   * @type {string}
   * @memberof BindAddressParamsData
   */
  pubkey?: string;
}
