/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface BUserStatus
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface BUserStatus {
  /**
   * 是否是通过认证的b端
   * @type {boolean}
   * @memberof BUserStatus
   */
  verified: boolean;
  /**
   * 是否有已创建的campaign(包含草稿和插件端的campaign，已删除的不算)
   * @type {boolean}
   * @memberof BUserStatus
   */
  have_created_campaigns: boolean;
}
