/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { UploadTask } from "./upload-task";

/**
 *
 * @export
 * @interface CampaignLotteryResp
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface CampaignLotteryResp {
  /**
   * 所有pow任务列表，包含未上传和上传过
   * @type {Array<UploadTask>}
   * @memberof CampaignLotteryResp
   */
  upload_tasks: Array<UploadTask>;
}
