/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface CampaignStatisticsInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface CampaignStatisticsInfo {
  /**
   *
   * @type {number}
   * @memberof CampaignStatisticsInfo
   */
  visitor_number: number;
  /**
   *
   * @type {number}
   * @memberof CampaignStatisticsInfo
   */
  participant_number: number;
  /**
   *
   * @type {number}
   * @memberof CampaignStatisticsInfo
   */
  sumbitter_number: number;
  /**
   *
   * @type {number}
   * @memberof CampaignStatisticsInfo
   */
  qualifier_number: number;
  /**
   *
   * @type {number}
   * @memberof CampaignStatisticsInfo
   */
  winner_number: number;
}
