/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface CampaignStatusInfoGenerated
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface CampaignStatusInfoGenerated {
  /**
   * 是否产生了winner
   * @type {boolean}
   * @memberof CampaignStatusInfoGenerated
   */
  winner_generated: boolean;
  /**
   * 是否产生了奖励
   * @type {boolean}
   * @memberof CampaignStatusInfoGenerated
   */
  reward_generated: boolean;
  /**
   * 所有的task是否都产生了qualifier
   * @type {boolean}
   * @memberof CampaignStatusInfoGenerated
   */
  all_task_qualifier_generated: boolean;
}
