/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { CampaignStatusInfoGenerated } from "./campaign-status-info-generated";
import { CampaignStatusInfoStatistics } from "./campaign-status-info-statistics";

/**
 *
 * @export
 * @interface CampaignStatusInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface CampaignStatusInfo {
  /**
   *
   * @type {CampaignStatusInfoStatistics}
   * @memberof CampaignStatusInfo
   */
  statistics: CampaignStatusInfoStatistics;
  /**
   *
   * @type {CampaignStatusInfoGenerated}
   * @memberof CampaignStatusInfo
   */
  generated: CampaignStatusInfoGenerated;
}
