/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Chain } from "./chain";
import { ChainType } from "./chain-type";

/**
 *
 * @export
 * @interface ChainInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface ChainInfo {
  /**
   * chain id，字符串
   * @type {string}
   * @memberof ChainInfo
   */
  id: string;
  /**
   *
   * @type {Chain}
   * @memberof ChainInfo
   */
  name: Chain;
  /**
   *
   * @type {ChainType}
   * @memberof ChainInfo
   */
  chain_type: ChainType;
  /**
   *
   * @type {string}
   * @memberof ChainInfo
   */
  icon: string;
  /**
   *
   * @type {string}
   * @memberof ChainInfo
   */
  label: string;
  /**
   * 用于mint nft的合约地址
   * @type {string}
   * @memberof ChainInfo
   */
  contract: string;
  /**
   * 用于前端显示的合约地址
   * @type {string}
   * @memberof ChainInfo
   */
  nft_contract: string;
  /**
   * nft是否支持在opensea查看
   * @type {boolean}
   * @memberof ChainInfo
   */
  is_support_opensea: boolean;
  /**
   * metamask配置数据
   * @type {string}
   * @memberof ChainInfo
   */
  rpc_url: string;
  /**
   *
   * @type {string}
   * @memberof ChainInfo
   */
  explorer_url: string;
  /**
   *
   * @type {string}
   * @memberof ChainInfo
   */
  coin_name: string;
  /**
   *
   * @type {string}
   * @memberof ChainInfo
   */
  coin_symbol: string;
  /**
   *
   * @type {number}
   * @memberof ChainInfo
   */
  coin_decimals: number;
  /**
   * token入金合约地址
   * @type {string}
   * @memberof ChainInfo
   */
  taskonfund_token_contract: string;
  /**
   * nft入金合约地址
   * @type {string}
   * @memberof ChainInfo
   */
  taskonfund_nft_contract: string;
}
