/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface CombineCampaignOperateTextItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface CombineCampaignOperateTextItem {
  /**
   * 活动id
   * @type {number}
   * @memberof CombineCampaignOperateTextItem
   */
  campaign_id: number;
  /**
   * 活动名称
   * @type {string}
   * @memberof CombineCampaignOperateTextItem
   */
  campaign_name: string;
  /**
   * 活动调整链接
   * @type {string}
   * @memberof CombineCampaignOperateTextItem
   */
  link_url: string;
}
