/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { AutomaticallyWinnerDrawType } from "./automatically-winner-draw-type";
import { RewardInfo } from "./reward-info";
import { WinnerDrawType } from "./winner-draw-type";

/**
 *
 * @export
 * @interface CreatorCampaignListItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface CreatorCampaignListItem {
  /**
   *
   * @type {number}
   * @memberof CreatorCampaignListItem
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof CreatorCampaignListItem
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreatorCampaignListItem
   */
  owner_id: string;
  /**
   * 未设置返回空字符串
   * @type {string}
   * @memberof CreatorCampaignListItem
   */
  owner_name: string;
  /**
   *
   * @type {string}
   * @memberof CreatorCampaignListItem
   */
  owner_avatar: string;
  /**
   *
   * @type {string}
   * @memberof CreatorCampaignListItem
   */
  owner_address: string;
  /**
   *
   * @type {string}
   * @memberof CreatorCampaignListItem
   */
  image: string;
  /**
   *
   * @type {boolean}
   * @memberof CreatorCampaignListItem
   */
  recaptcha: boolean;
  /**
   *
   * @type {boolean}
   * @memberof CreatorCampaignListItem
   */
  is_draft: boolean;
  /**
   *
   * @type {boolean}
   * @memberof CreatorCampaignListItem
   */
  is_removed: boolean;
  /**
   *
   * @type {boolean}
   * @memberof CreatorCampaignListItem
   */
  is_end: boolean;
  /**
   *
   * @type {number}
   * @memberof CreatorCampaignListItem
   */
  campaign_level: number;
  /**
   * 活动开始时间
   * @type {number}
   * @memberof CreatorCampaignListItem
   */
  start_time: number;
  /**
   * 活动结束时间
   * @type {number}
   * @memberof CreatorCampaignListItem
   */
  end_time: number;
  /**
   * 活动最大的winner 人数
   * @type {string}
   * @memberof CreatorCampaignListItem
   */
  max_winners: string;
  /**
   *
   * @type {WinnerDrawType}
   * @memberof CreatorCampaignListItem
   */
  winner_draw_type: WinnerDrawType;
  /**
   *
   * @type {AutomaticallyWinnerDrawType}
   * @memberof CreatorCampaignListItem
   */
  automatically_winner_draw_type: AutomaticallyWinnerDrawType;
  /**
   *
   * @type {Array<RewardInfo>}
   * @memberof CreatorCampaignListItem
   */
  qualifier_rewards?: Array<RewardInfo>;
  /**
   *
   * @type {Array<RewardInfo>}
   * @memberof CreatorCampaignListItem
   */
  winner_rewards?: Array<RewardInfo>;
  /**
   *
   * @type {number}
   * @memberof CreatorCampaignListItem
   */
  participate_count: number;
  /**
   * 未上传的pow task 数量
   * @type {number}
   * @memberof CreatorCampaignListItem
   */
  unupload_pow_count: number;
  /**
   * 是否需要上传winner列表
   * @type {boolean}
   * @memberof CreatorCampaignListItem
   */
  need_upload_winner: boolean;
  /**
   * 是否需要上传reward token列表
   * @type {boolean}
   * @memberof CreatorCampaignListItem
   */
  need_upload_winner_reward: boolean;
  /**
   *
   * @type {string}
   * @memberof CreatorCampaignListItem
   */
  airdrop_tool?: string;
}
