/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface CreateCampaignNotiType
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface CreateCampaignNotiType {
  /**
   *
   * @type {number}
   * @memberof CreateCampaignNotiType
   */
  campaign_id: number;
  /**
   *
   * @type {string}
   * @memberof CreateCampaignNotiType
   */
  campaign_name: string;
  /**
   *
   * @type {number}
   * @memberof CreateCampaignNotiType
   */
  reward_token_id: number;
  /**
   *
   * @type {string}
   * @memberof CreateCampaignNotiType
   */
  reward_token_name: string;
  /**
   *
   * @type {number}
   * @memberof CreateCampaignNotiType
   */
  reward_token_decimal: number;
  /**
   *
   * @type {string}
   * @memberof CreateCampaignNotiType
   */
  reward_token_amount: string;
}
