/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface DefaultTokenInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface DefaultTokenInfo {
  /**
   *
   * @type {string}
   * @memberof DefaultTokenInfo
   */
  token_view: string;
  /**
   *
   * @type {string}
   * @memberof DefaultTokenInfo
   */
  token_name: string;
  /**
   *
   * @type {string}
   * @memberof DefaultTokenInfo
   */
  chain_name: string;
  /**
   *
   * @type {string}
   * @memberof DefaultTokenInfo
   */
  contract_addr: string;
  /**
   *
   * @type {number}
   * @memberof DefaultTokenInfo
   */
  decimals: number;
}
