/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Chain } from "./chain";
import { NftType } from "./nft-type";

/**
 *
 * @export
 * @interface DefaultNftInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface DefaultNftInfo {
  /**
   *
   * @type {string}
   * @memberof DefaultNftInfo
   */
  nft_name: string;
  /**
   *
   * @type {string}
   * @memberof DefaultNftInfo
   */
  contract_addr: string;
  /**
   *
   * @type {Chain}
   * @memberof DefaultNftInfo
   */
  chain_name: Chain;
  /**
   *
   * @type {NftType}
   * @memberof DefaultNftInfo
   */
  nft_type: NftType;
}
