/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { CampaignDataType } from "./campaign-data-type";

/**
 *
 * @export
 * @interface DownloadCampaignDataParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface DownloadCampaignDataParams {
  /**
   *
   * @type {number}
   * @memberof DownloadCampaignDataParams
   */
  campaign_id: number;
  /**
   *
   * @type {CampaignDataType}
   * @memberof DownloadCampaignDataParams
   */
  data_type: CampaignDataType;
}
