/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * EditUserInfo编辑用户信息参数
 * @export
 * @interface EditUserInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface EditUserInfo {
  /**
   * 不填时不更新
   * @type {string}
   * @memberof EditUserInfo
   */
  user_name?: string;
  /**
   * 不填时不更新，空字符串时表示删除头像
   * @type {string}
   * @memberof EditUserInfo
   */
  avatar?: string;
}
