/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { EligibilityType } from "./eligibility-type";

/**
 *
 * @export
 * @interface EligibilityItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface EligibilityItem {
  /**
   *
   * @type {number}
   * @memberof EligibilityItem
   */
  id: number;
  /**
   * json字符串 TokenBalanceEligibility，SpecificNftHolderEligibility，MinUserLevelEligibility
   * @type {string}
   * @memberof EligibilityItem
   */
  params: string;
  /**
   *
   * @type {EligibilityType}
   * @memberof EligibilityItem
   */
  type: EligibilityType;
}
