/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @enum {string}
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export enum ErrorCode {
  TWITTER_USER_TOO_MANY_REQUESTS = "TWITTER_USER_TOO_MANY_REQUESTS",
  TWITTER_UNAUTHORIZED = "TWITTER_UNAUTHORIZED",
  DISCORD_UNAUTHORIZED = "DISCORD_UNAUTHORIZED",
  CAMPAIGN_NOT_EXIST = "CAMPAIGN_NOT_EXIST",
  INVALID_ADDRESS = "INVALID_ADDRESS",
  EXISTED_ITEM = "EXISTED_ITEM",
  HANDLE_NOT_EXIST = "HANDLE_NOT_EXIST",
  HANDLE_ACCOUNT_NOT_EXIST = "HANDLE_ACCOUNT_NOT_EXIST",
}
