/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @enum {string}
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export enum ErrorCode {
  TWITTERUSERTOOMANYREQUESTS = "TWITTER_USER_TOO_MANY_REQUESTS",
  TWITTERUNAUTHORIZED = "TWITTER_UNAUTHORIZED",
  DISCORDUNAUTHORIZED = "DISCORD_UNAUTHORIZED",
  CAMPAIGNNOTEXIST = "CAMPAIGN_NOT_EXIST",
  INVALIDADDRESS = "INVALID_ADDRESS",
  EXISTEDITEM = "EXISTED_ITEM",
  HANDLENOTEXIST = "HANDLE_NOT_EXIST",
  HANDLEACCOUNTNOTEXIST = "HANDLE_ACCOUNT_NOT_EXIST",
}
