/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface FollowTwitterTaskValue
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface FollowTwitterTaskValue {
  /**
   *
   * @type {string}
   * @memberof FollowTwitterTaskValue
   */
  project_name: string;
  /**
   *
   * @type {string}
   * @memberof FollowTwitterTaskValue
   */
  user_to_follow: string;
  /**
   *
   * @type {string}
   * @memberof FollowTwitterTaskValue
   */
  user_to_follow_id: string;
}
