/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Page } from "./page";
import { TokenAddress } from "./token-address";

/**
 *
 * @export
 * @interface GetRewardTokenAmountParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface GetRewardTokenAmountParams {
  /**
   *
   * @type {TokenAddress}
   * @memberof GetRewardTokenAmountParams
   */
  token_address: TokenAddress;
  /**
   *
   * @type {Page}
   * @memberof GetRewardTokenAmountParams
   */
  page: Page;
}
