/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { TxStatus } from "./tx-status";
import { TxType } from "./tx-type";

/**
 *
 * @export
 * @interface GetUserNftTxHistoryParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface GetUserNftTxHistoryParams {
  /**
   *
   * @type {TxType}
   * @memberof GetUserNftTxHistoryParams
   */
  tx_type: TxType;
  /**
   *
   * @type {TxStatus}
   * @memberof GetUserNftTxHistoryParams
   */
  tx_status: TxStatus;
  /**
   * 0表示所有
   * @type {number}
   * @memberof GetUserNftTxHistoryParams
   */
  nft_collection_id: number;
}
