/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Page } from "./page";
import { UserTaskStatus } from "./user-task-status";

/**
 *
 * @export
 * @interface GetTaskUserListParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface GetTaskUserListParams {
  /**
   *
   * @type {number}
   * @memberof GetTaskUserListParams
   */
  task_id: number;
  /**
   *
   * @type {UserTaskStatus}
   * @memberof GetTaskUserListParams
   */
  user_task_status: UserTaskStatus;
  /**
   *
   * @type {Page}
   * @memberof GetTaskUserListParams
   */
  page: Page;
}
