/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { InlineResponse20035Error } from "./inline-response20035-error";

/**
 *
 * @export
 * @interface InlineResponse20035
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface InlineResponse20035 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20035
   */
  result: string;
  /**
   *
   * @type {InlineResponse20035Error}
   * @memberof InlineResponse20035
   */
  error: InlineResponse20035Error;
}
