/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface InlineObject8
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface InlineObject8 {
  /**
   *
   * @type {any}
   * @memberof InlineObject8
   */
  file: any;
  /**
   * campaign/nft/avatar/pow/text
   * @type {string}
   * @memberof InlineObject8
   */
  imageType: string;
}
