/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { InlineResponse200Error1 } from "./inline-response200-error1";

/**
 *
 * @export
 * @interface InlineResponse2003
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface InlineResponse2003 {
  /**
   *
   * @type {InlineResponse200Error1}
   * @memberof InlineResponse2003
   */
  error1?: InlineResponse200Error1;
  /**
   * 0表示没有未发布的活动，否则为未发布的活动Id
   * @type {number}
   * @memberof InlineResponse2003
   */
  result: number;
}
