/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Page } from "./page";
import { RewardType } from "./reward-type";

/**
 *
 * @export
 * @interface InlineObject6
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface InlineObject6 {
  /**
   *
   * @type {RewardType}
   * @memberof InlineObject6
   */
  reward_type: RewardType;
  /**
   *
   * @type {Page}
   * @memberof InlineObject6
   */
  page: Page;
}
