/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Page } from "./page";

/**
 *
 * @export
 * @interface InlineObject31
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface InlineObject31 {
  /**
   *
   * @type {Page}
   * @memberof InlineObject31
   */
  page?: Page;
  /**
   * 0表示所有
   * @type {number}
   * @memberof InlineObject31
   */
  token_id?: number;
}
