/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { InlineResponse20029Result } from "./inline-response20029-result";
import { InlineResponse200Error1 } from "./inline-response200-error1";

/**
 *
 * @export
 * @interface InlineResponse20029
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface InlineResponse20029 {
  /**
   *
   * @type {InlineResponse20029Result}
   * @memberof InlineResponse20029
   */
  result?: InlineResponse20029Result;
  /**
   *
   * @type {InlineResponse200Error1}
   * @memberof InlineResponse20029
   */
  error?: InlineResponse200Error1;
}
