/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { ErrorCode } from "./error-code";

/**
 *
 * @export
 * @interface InlineResponse20049
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface InlineResponse20049 {
  /**
   *
   * @type {boolean}
   * @memberof InlineResponse20049
   */
  result?: boolean;
  /**
   *
   * @type {ErrorCode}
   * @memberof InlineResponse20049
   */
  error?: ErrorCode;
}
