/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { V1SubmitChallengeProof } from "./v1-submit-challenge-proof";

/**
 *
 * @export
 * @interface InlineObject1
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface InlineObject1 {
  /**
   *
   * @type {string}
   * @memberof InlineObject1
   */
  ver: string;
  /**
   *
   * @type {string}
   * @memberof InlineObject1
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof InlineObject1
   */
  nonce: string;
  /**
   *
   * @type {string}
   * @memberof InlineObject1
   */
  did: string;
  /**
   *
   * @type {V1SubmitChallengeProof}
   * @memberof InlineObject1
   */
  proof: V1SubmitChallengeProof;
  /**
   * 空数组
   * @type {Array<string>}
   * @memberof InlineObject1
   */
  VPs: Array<string>;
  /**
   * aptos必需
   * @type {string}
   * @memberof InlineObject1
   */
  pubkey?: string;
}
