/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface JoinTelegramTaskParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface JoinTelegramTaskParams {
  /**
   *
   * @type {boolean}
   * @memberof JoinTelegramTaskParams
   */
  is_public: boolean;
  /**
   *
   * @type {string}
   * @memberof JoinTelegramTaskParams
   */
  channel_name: string;
  /**
   *
   * @type {string}
   * @memberof JoinTelegramTaskParams
   */
  telegram_link: string;
  /**
   *
   * @type {string}
   * @memberof JoinTelegramTaskParams
   */
  extra?: string;
}
