/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { DiscordRole } from "./discord-role";

/**
 *
 * @export
 * @interface JoinDiscordTaskValue
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface JoinDiscordTaskValue {
  /**
   *
   * @type {string}
   * @memberof JoinDiscordTaskValue
   */
  project_name: string;
  /**
   *
   * @type {string}
   * @memberof JoinDiscordTaskValue
   */
  discord_server: string;
  /**
   *
   * @type {string}
   * @memberof JoinDiscordTaskValue
   */
  invite_link: string;
  /**
   *
   * @type {Array<DiscordRole>}
   * @memberof JoinDiscordTaskValue
   */
  roles?: Array<DiscordRole>;
}
