/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface LinkTaskParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface LinkTaskParams {
  /**
   *
   * @type {string}
   * @memberof LinkTaskParams
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof LinkTaskParams
   */
  link_label: string;
  /**
   *
   * @type {string}
   * @memberof LinkTaskParams
   */
  link: string;
  /**
   *
   * @type {string}
   * @memberof LinkTaskParams
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof LinkTaskParams
   */
  extra?: string;
}
