/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface LockedTokenListItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface LockedTokenListItem {
  /**
   *
   * @type {number}
   * @memberof LockedTokenListItem
   */
  campaign_id: number;
  /**
   *
   * @type {string}
   * @memberof LockedTokenListItem
   */
  campaign_name: string;
  /**
   *
   * @type {string}
   * @memberof LockedTokenListItem
   */
  locked_amount: string;
  /**
   * 毫秒时间值
   * @type {number}
   * @memberof LockedTokenListItem
   */
  lock_time: number;
}
