/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface LockedNftListItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface LockedNftListItem {
  /**
   *
   * @type {number}
   * @memberof LockedNftListItem
   */
  collection_id: number;
  /**
   *
   * @type {string}
   * @memberof LockedNftListItem
   */
  collection_name: string;
  /**
   *
   * @type {string}
   * @memberof LockedNftListItem
   */
  token_id: string;
  /**
   *
   * @type {number}
   * @memberof LockedNftListItem
   */
  quantity: number;
  /**
   *
   * @type {number}
   * @memberof LockedNftListItem
   */
  campaign_id: number;
  /**
   *
   * @type {string}
   * @memberof LockedNftListItem
   */
  campaign_name: string;
}
