/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * 最小用户等级
 * @export
 * @interface MinUserLevelEligibilityParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface MinUserLevelEligibilityParams {
  /**
   * 最小用户等级
   * @type {number}
   * @memberof MinUserLevelEligibilityParams
   */
  level: number;
  /**
   *
   * @type {string}
   * @memberof MinUserLevelEligibilityParams
   */
  extra?: string;
}
