/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface NftTokenIdListItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface NftTokenIdListItem {
  /**
   *
   * @type {number}
   * @memberof NftTokenIdListItem
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof NftTokenIdListItem
   */
  collection_name: string;
  /**
   *
   * @type {string}
   * @memberof NftTokenIdListItem
   */
  token_id: string;
  /**
   *
   * @type {number}
   * @memberof NftTokenIdListItem
   */
  avail_quantity: number;
  /**
   *
   * @type {number}
   * @memberof NftTokenIdListItem
   */
  total_quantity: number;
  /**
   *
   * @type {number}
   * @memberof NftTokenIdListItem
   */
  locked_quantity: number;
  /**
   *
   * @type {number}
   * @memberof NftTokenIdListItem
   */
  campaign_id: number;
  /**
   *
   * @type {string}
   * @memberof NftTokenIdListItem
   */
  campaign_name: string;
}
