/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { NftWithdrawTokenId } from "./nft-withdraw-token-id";

/**
 *
 * @export
 * @interface NftWithdrawParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface NftWithdrawParams {
  /**
   *
   * @type {string}
   * @memberof NftWithdrawParams
   */
  chain: string;
  /**
   *
   * @type {number}
   * @memberof NftWithdrawParams
   */
  collection_id: number;
  /**
   *
   * @type {string}
   * @memberof NftWithdrawParams
   */
  recevie_address: string;
  /**
   *
   * @type {Array<NftWithdrawTokenId>}
   * @memberof NftWithdrawParams
   */
  token_ids: Array<NftWithdrawTokenId>;
}
