/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { CompletedCampaignNotiType } from "./completed-campaign-noti-type";
import { CreateCampaignNotiType } from "./create-campaign-noti-type";
import { JoinCampaignNotiType } from "./join-campaign-noti-type";
import { LotteryWinnerNotiType } from "./lottery-winner-noti-type";
import { NotificationType } from "./notification-type";
import { PayCampaignNotiType } from "./pay-campaign-noti-type";

/**
 *
 * @export
 * @interface NotificationInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface NotificationInfo {
  /**
   *
   * @type {number}
   * @memberof NotificationInfo
   */
  id: number;
  /**
   *
   * @type {NotificationType}
   * @memberof NotificationInfo
   */
  type: NotificationType;
  /**
   *
   * @type {PayCampaignNotiType | CreateCampaignNotiType | CompletedCampaignNotiType | LotteryWinnerNotiType | JoinCampaignNotiType}
   * @memberof NotificationInfo
   */
  content:
    | PayCampaignNotiType
    | CreateCampaignNotiType
    | CompletedCampaignNotiType
    | LotteryWinnerNotiType
    | JoinCampaignNotiType;
  /**
   *
   * @type {number}
   * @memberof NotificationInfo
   */
  timestamp: number;
  /**
   * read or unread
   * @type {boolean}
   * @memberof NotificationInfo
   */
  status: boolean;
}
