/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface OuterApiTaskParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface OuterApiTaskParams {
  /**
   *
   * @type {string}
   * @memberof OuterApiTaskParams
   */
  api_url: string;
  /**
   * 对应产品的targetUrl
   * @type {string}
   * @memberof OuterApiTaskParams
   */
  target_url: string;
  /**
   *
   * @type {string}
   * @memberof OuterApiTaskParams
   */
  extra?: string;
  /**
   *
   * @type {string}
   * @memberof OuterApiTaskParams
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof OuterApiTaskParams
   */
  icon?: string;
  /**
   *
   * @type {string}
   * @memberof OuterApiTaskParams
   */
  desc?: string;
}
