/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { TokenInfo } from "./token-info";

/**
 *
 * @export
 * @interface PluginConfigInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface PluginConfigInfo {
  /**
   *
   * @type {string}
   * @memberof PluginConfigInfo
   */
  contract_address: string;
  /**
   *
   * @type {string}
   * @memberof PluginConfigInfo
   */
  rpc_url: string;
  /**
   *
   * @type {string}
   * @memberof PluginConfigInfo
   */
  chain_id: string;
  /**
   *
   * @type {string}
   * @memberof PluginConfigInfo
   */
  chain_id_hex: string;
  /**
   *
   * @type {string}
   * @memberof PluginConfigInfo
   */
  explorer_url: string;
  /**
   *
   * @type {string}
   * @memberof PluginConfigInfo
   */
  chain_name: string;
  /**
   *
   * @type {string}
   * @memberof PluginConfigInfo
   */
  chain_symbol: string;
  /**
   *
   * @type {string}
   * @memberof PluginConfigInfo
   */
  default_token_address: string;
  /**
   *
   * @type {TokenInfo}
   * @memberof PluginConfigInfo
   */
  native_token: TokenInfo;
}
