/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { PowTaskType } from "./pow-task-type";

/**
 *
 * @export
 * @interface PowTaskValue
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface PowTaskValue {
  /**
   *
   * @type {string}
   * @memberof PowTaskValue
   */
  desc: string;
  /**
   *
   * @type {PowTaskType}
   * @memberof PowTaskValue
   */
  type: PowTaskType;
}
