/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface QuoteAndTagTaskValue
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface QuoteAndTagTaskValue {
  /**
   *
   * @type {string}
   * @memberof QuoteAndTagTaskValue
   */
  twitter_handle: string;
  /**
   *
   * @type {string}
   * @memberof QuoteAndTagTaskValue
   */
  tweet_id: string;
  /**
   *
   * @type {string}
   * @memberof QuoteAndTagTaskValue
   */
  tags_users?: string;
  /**
   *
   * @type {number}
   * @memberof QuoteAndTagTaskValue
   */
  friends_count?: number;
}
