/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface QuoteAndTagTaskParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface QuoteAndTagTaskParams {
  /**
   *
   * @type {string}
   * @memberof QuoteAndTagTaskParams
   */
  twitter_link: string;
  /**
   * tags 和 friends_count 为互斥关系，如果有冲突tags优先 tags为逗号分隔的twitterhandle 字符串
   * @type {string}
   * @memberof QuoteAndTagTaskParams
   */
  tags?: string;
  /**
   *
   * @type {string}
   * @memberof QuoteAndTagTaskParams
   */
  extra?: string;
  /**
   * 默认值为0，表示没有friend count
   * @type {number}
   * @memberof QuoteAndTagTaskParams
   */
  friends_count?: number;
}
