/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * RewardTokenAmountInfo
 * @export
 * @interface RewardTokenAmountInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface RewardTokenAmountInfo {
  /**
   *
   * @type {string}
   * @memberof RewardTokenAmountInfo
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof RewardTokenAmountInfo
   */
  decimals: number;
  /**
   *
   * @type {string}
   * @memberof RewardTokenAmountInfo
   */
  chain: string;
  /**
   *
   * @type {string}
   * @memberof RewardTokenAmountInfo
   */
  contract_address: string;
  /**
   * 带精度int
   * @type {string}
   * @memberof RewardTokenAmountInfo
   */
  amount: string;
}
