/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { RewardDistributedByType } from "./reward-distributed-by-type";
import { RewardExpParameters } from "./reward-exp-parameters";
import { RewardNftParameters } from "./reward-nft-parameters";
import { RewardTokenParameters } from "./reward-token-parameters";
import { RewardType } from "./reward-type";
import { RewardWhitelistParameters } from "./reward-whitelist-parameters";
import { RewardsDistributeType } from "./rewards-distribute-type";

/**
 *
 * @export
 * @interface RewardInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface RewardInfo {
  /**
   *
   * @type {RewardType}
   * @memberof RewardInfo
   */
  reward_type: RewardType;
  /**
   *
   * @type {RewardTokenParameters | RewardNftParameters | RewardExpParameters | RewardWhitelistParameters}
   * @memberof RewardInfo
   */
  reward_params:
    | RewardTokenParameters
    | RewardNftParameters
    | RewardExpParameters
    | RewardWhitelistParameters;
  /**
   *
   * @type {RewardsDistributeType}
   * @memberof RewardInfo
   */
  reward_distribute_type: RewardsDistributeType;
  /**
   *
   * @type {RewardDistributedByType}
   * @memberof RewardInfo
   */
  reward_distributed_by_type: RewardDistributedByType;
  /**
   * reward desc
   * @type {string}
   * @memberof RewardInfo
   */
  reward_desc: string;
}
