/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Chain } from "./chain";
import { TokenType } from "./token-type";

/**
 *
 * @export
 * @interface RewardTokenParameters
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface RewardTokenParameters {
  /**
   *
   * @type {Chain}
   * @memberof RewardTokenParameters
   */
  chain: Chain;
  /**
   *
   * @type {string}
   * @memberof RewardTokenParameters
   */
  token_name: string;
  /**
   *
   * @type {string}
   * @memberof RewardTokenParameters
   */
  token_address: string;
  /**
   * -1代表all
   * @type {string}
   * @memberof RewardTokenParameters
   */
  total_amount: string;
  /**
   * total amount per winner
   * @type {string}
   * @memberof RewardTokenParameters
   */
  per_amount: string;
  /**
   *
   * @type {TokenType}
   * @memberof RewardTokenParameters
   */
  token_type: TokenType;
}
