/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { RewardWhiteListType } from "./reward-white-list-type";

/**
 *
 * @export
 * @interface RewardWhitelistParameters
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface RewardWhitelistParameters {
  /**
   *
   * @type {RewardWhiteListType}
   * @memberof RewardWhitelistParameters
   */
  white_list_type: RewardWhiteListType;
  /**
   *
   * @type {string}
   * @memberof RewardWhitelistParameters
   */
  chain: string;
  /**
   *
   * @type {string}
   * @memberof RewardWhitelistParameters
   */
  nft_image: string;
}
