/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface RewardNftValue
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface RewardNftValue {
  /**
   * nft claim tx_hash
   * @type {string}
   * @memberof RewardNftValue
   */
  tx_hash: string;
  /**
   * nft token id
   * @type {string}
   * @memberof RewardNftValue
   */
  token_id: string;
}
