/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Chain } from "./chain";
import { NftRewardTokenId } from "./nft-reward-token-id";
import { RewardOwnBy } from "./reward-own-by";

/**
 *
 * @export
 * @interface RewardNftParameters
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface RewardNftParameters {
  /**
   *
   * @type {string}
   * @memberof RewardNftParameters
   */
  nft_cdn_image: string;
  /**
   *
   * @type {string}
   * @memberof RewardNftParameters
   */
  nft_ipfs_image: string;
  /**
   *
   * @type {Chain}
   * @memberof RewardNftParameters
   */
  chain: Chain;
  /**
   *
   * @type {RewardOwnBy}
   * @memberof RewardNftParameters
   */
  own_by_type: RewardOwnBy;
  /**
   * nft collection address, 对于cap 填空字符串
   * @type {string}
   * @memberof RewardNftParameters
   */
  nft_address: string;
  /**
   *
   * @type {Array<NftRewardTokenId>}
   * @memberof RewardNftParameters
   */
  token_ids: Array<NftRewardTokenId>;
}
