/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { AutomaticallyWinnerDrawType } from "./automatically-winner-draw-type";
import { EligibilityParamItem } from "./eligibility-param-item";
import { RewardInfo } from "./reward-info";
import { TaskParamItem } from "./task-param-item";
import { WinnerDrawType } from "./winner-draw-type";

/**
 *
 * @export
 * @interface SetCampaignParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface SetCampaignParams {
  /**
   * campaignId， 0表示创建，其他表示修改活动
   * @type {number}
   * @memberof SetCampaignParams
   */
  id: number;
  /**
   * 活动owner 的user id
   * @type {number}
   * @memberof SetCampaignParams
   */
  owner_id: number;
  /**
   * 活动名称
   * @type {string}
   * @memberof SetCampaignParams
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof SetCampaignParams
   */
  desc: string;
  /**
   *
   * @type {number}
   * @memberof SetCampaignParams
   */
  campaign_start: number;
  /**
   *
   * @type {number}
   * @memberof SetCampaignParams
   */
  campaign_end: number;
  /**
   *
   * @type {string}
   * @memberof SetCampaignParams
   */
  campaign_image: string;
  /**
   *
   * @type {boolean}
   * @memberof SetCampaignParams
   */
  google_recaptcha: boolean;
  /**
   *
   * @type {boolean}
   * @memberof SetCampaignParams
   */
  is_draft: boolean;
  /**
   * 活动前置条件表达式，or 或者 and
   * @type {string}
   * @memberof SetCampaignParams
   */
  eligibility_express: string;
  /**
   * 最大winner人数，0 表示不限制
   * @type {number}
   * @memberof SetCampaignParams
   */
  max_winners: number;
  /**
   *
   * @type {WinnerDrawType}
   * @memberof SetCampaignParams
   */
  winner_draw_type: WinnerDrawType;
  /**
   *
   * @type {AutomaticallyWinnerDrawType}
   * @memberof SetCampaignParams
   */
  automatically_winner_draw_type: AutomaticallyWinnerDrawType;
  /**
   *
   * @type {Array<RewardInfo>}
   * @memberof SetCampaignParams
   */
  winner_rewards: Array<RewardInfo>;
  /**
   * 活动前置条件
   * @type {Array<EligibilityParamItem>}
   * @memberof SetCampaignParams
   */
  eligs: Array<EligibilityParamItem>;
  /**
   *
   * @type {Array<TaskParamItem>}
   * @memberof SetCampaignParams
   */
  tasks: Array<TaskParamItem>;
}
