/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface SpecificNftHolderTaskValue
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface SpecificNftHolderTaskValue {
  /**
   *
   * @type {string}
   * @memberof SpecificNftHolderTaskValue
   */
  pick_from_list: string;
  /**
   *
   * @type {string}
   * @memberof SpecificNftHolderTaskValue
   */
  nft_address: string;
  /**
   *
   * @type {string}
   * @memberof SpecificNftHolderTaskValue
   */
  chain: string;
  /**
   *
   * @type {string}
   * @memberof SpecificNftHolderTaskValue
   */
  nft_type: string;
  /**
   *
   * @type {number}
   * @memberof SpecificNftHolderTaskValue
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof SpecificNftHolderTaskValue
   */
  nft_name: string;
  /**
   *
   * @type {string}
   * @memberof SpecificNftHolderTaskValue
   */
  chain_label: string;
}
