/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Country } from "./country";
import { SupportedCountryType } from "./supported-country-type";

/**
 *
 * @export
 * @interface SupportedCountry
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface SupportedCountry {
  /**
   *
   * @type {SupportedCountryType}
   * @memberof SupportedCountry
   */
  type: SupportedCountryType;
  /**
   *
   * @type {Array<Country>}
   * @memberof SupportedCountry
   */
  supported_country: Array<Country>;
  /**
   *
   * @type {string}
   * @memberof SupportedCountry
   */
  extra?: string;
}
