/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { TaskTemplateId } from "./task-template-id";

/**
 *
 * @export
 * @interface TaskValueItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface TaskValueItem {
  /**
   * Task Id
   * @type {number}
   * @memberof TaskValueItem
   */
  id: number;
  /**
   *
   * @type {TaskTemplateId}
   * @memberof TaskValueItem
   */
  template_id: TaskTemplateId;
  /**
   * Task json 字符串
   * @type {string}
   * @memberof TaskValueItem
   */
  params: string;
}
