/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @enum {string}
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export enum TaskTemplateId1 {
  A001_1 = "A001-1",
  A001_2 = "A001-2",
  A001_3 = "A001-3",
  A001_4 = "A001-4",
  A001_5 = "A001-5",
  A001_6 = "A001-6",
  A001_7 = "A001-7",
  A001_8 = "A001-8",
  A001_9 = "A001-9",
  A001_10 = "A001-10",
  A002_1 = "A002-1",
  A002_2 = "A002-2",
  B001 = "B001",
  M001 = "M001",
  N001 = "N001",
  N002 = "N002",
  N003 = "N003",
  N004 = "N004",
}
