/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @enum {string}
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export enum TaskTemplateId1 {
  A0011 = "A001-1",
  A0012 = "A001-2",
  A0013 = "A001-3",
  A0014 = "A001-4",
  A0015 = "A001-5",
  A0016 = "A001-6",
  A0017 = "A001-7",
  A0018 = "A001-8",
  A0019 = "A001-9",
  A00110 = "A001-10",
  A0021 = "A002-1",
  A0022 = "A002-2",
  B001 = "B001",
  M001 = "M001",
  N001 = "N001",
  N002 = "N002",
  N003 = "N003",
  N004 = "N004",
}
