/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface TaskSelectOption
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface TaskSelectOption {
  /**
   * TaskId
   * @type {number}
   * @memberof TaskSelectOption
   */
  id: number;
  /**
   * Task TemplateId
   * @type {string}
   * @memberof TaskSelectOption
   */
  template_id: string;
  /**
   * task  params json字符串
   * @type {string}
   * @memberof TaskSelectOption
   */
  params: string;
}
