/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * TaskTemplateId枚举
 * @export
 * @enum {string}
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export enum TaskTemplateId {
  FollowTwitter = "FollowTwitter",
  RetweetTwitter = "RetweetTwitter",
  QuoteTweetAndTag = "QuoteTweetAndTag",
  JoinDiscord = "JoinDiscord",
  NftHolder = "NftHolder",
  TokenBalance = "TokenBalance",
  PowTask = "PowTask",
  PowQa = "PowQa",
  LinkTask = "LinkTask",
  JoinTelegram = "JoinTelegram",
  OuterAPI = "OuterAPI",
  LikeATweet = "LikeATweet",
}
