/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface TaskUserListItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface TaskUserListItem {
  /**
   *
   * @type {number}
   * @memberof TaskUserListItem
   */
  user_id: number;
  /**
   *
   * @type {string}
   * @memberof TaskUserListItem
   */
  avatar: string;
  /**
   *
   * @type {string}
   * @memberof TaskUserListItem
   */
  address: string;
  /**
   *
   * @type {number}
   * @memberof TaskUserListItem
   */
  campaign_id: number;
  /**
   *
   * @type {string}
   * @memberof TaskUserListItem
   */
  campaign_name: string;
  /**
   * 参与时间
   * @type {number}
   * @memberof TaskUserListItem
   */
  participate_time: number;
  /**
   *
   * @type {number}
   * @memberof TaskUserListItem
   */
  task_id: number;
}
