/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { Chain } from "./chain";

/**
 *
 * @export
 * @interface TokenInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface TokenInfo {
  /**
   *
   * @type {number}
   * @memberof TokenInfo
   */
  id: number;
  /**
   *
   * @type {Chain}
   * @memberof TokenInfo
   */
  chain: Chain;
  /**
   *
   * @type {string}
   * @memberof TokenInfo
   */
  address: string;
  /**
   *
   * @type {string}
   * @memberof TokenInfo
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof TokenInfo
   */
  symbol: string;
  /**
   *
   * @type {number}
   * @memberof TokenInfo
   */
  decimals: number;
  /**
   *
   * @type {string}
   * @memberof TokenInfo
   */
  logo: string;
  /**
   *
   * @type {string}
   * @memberof TokenInfo
   */
  thumbnail: string;
}
