/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface TokenBalanceEligibilityParams1
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface TokenBalanceEligibilityParams1 {
  /**
   *
   * @type {number}
   * @memberof TokenBalanceEligibilityParams1
   */
  index: number;
  /**
   *
   * @type {boolean}
   * @memberof TokenBalanceEligibilityParams1
   */
  pick_from_list: boolean;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityParams1
   */
  token_name: string;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityParams1
   */
  token_contract_addr: string;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityParams1
   */
  network: string;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityParams1
   */
  min_balance: string;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityParams1
   */
  extra?: string;
}
