/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface TokenBalanceEligibilityValue
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface TokenBalanceEligibilityValue {
  /**
   *
   * @type {boolean}
   * @memberof TokenBalanceEligibilityValue
   */
  pick_from_list: boolean;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityValue
   */
  token_name: string;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityValue
   */
  token_address: string;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityValue
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityValue
   */
  chain: string;
  /**
   *
   * @type {string}
   * @memberof TokenBalanceEligibilityValue
   */
  chain_label: string;
}
