/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { TxType } from "./tx-type";

/**
 *
 * @export
 * @interface TokenDistributeRewardDetail
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface TokenDistributeRewardDetail {
  /**
   *
   * @type {string}
   * @memberof TokenDistributeRewardDetail
   */
  chain: string;
  /**
   *
   * @type {string}
   * @memberof TokenDistributeRewardDetail
   */
  chain_label: string;
  /**
   *
   * @type {string}
   * @memberof TokenDistributeRewardDetail
   */
  token_symbol: string;
  /**
   *
   * @type {string}
   * @memberof TokenDistributeRewardDetail
   */
  token_icon: string;
  /**
   *
   * @type {string}
   * @memberof TokenDistributeRewardDetail
   */
  total_amount: string;
  /**
   *
   * @type {number}
   * @memberof TokenDistributeRewardDetail
   */
  campaign_id: number;
  /**
   *
   * @type {string}
   * @memberof TokenDistributeRewardDetail
   */
  campaign_name: string;
  /**
   *
   * @type {TxType}
   * @memberof TokenDistributeRewardDetail
   */
  tx_type: TxType;
  /**
   * 毫秒值时间
   * @type {number}
   * @memberof TokenDistributeRewardDetail
   */
  distribute_time: number;
}
