/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { ChainType } from "./chain-type";

/**
 *
 * @export
 * @interface UnbindAddressParams
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UnbindAddressParams {
  /**
   *
   * @type {ChainType}
   * @memberof UnbindAddressParams
   */
  chain_type: ChainType;
  /**
   *
   * @type {string}
   * @memberof UnbindAddressParams
   */
  address: string;
}
