/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * UploadTask
 * @export
 * @interface UploadTask
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UploadTask {
  /**
   *
   * @type {number}
   * @memberof UploadTask
   */
  task_id: number;
  /**
   *
   * @type {string}
   * @memberof UploadTask
   */
  task_name: string;
  /**
   *
   * @type {string}
   * @memberof UploadTask
   */
  description: string;
  /**
   *
   * @type {boolean}
   * @memberof UploadTask
   */
  compeleted: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UploadTask
   */
  confirm: boolean;
  /**
   *
   * @type {string}
   * @memberof UploadTask
   */
  file_name: string;
  /**
   *
   * @type {number}
   * @memberof UploadTask
   */
  upload_amount: number;
  /**
   *
   * @type {number}
   * @memberof UploadTask
   */
  upload_time: number;
}
