/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * UploadQualifierListReponse
 * @export
 * @interface UploadQualifierListReponse
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UploadQualifierListReponse {
  /**
   *
   * @type {number}
   * @memberof UploadQualifierListReponse
   */
  submit_time: number;
  /**
   *
   * @type {string}
   * @memberof UploadQualifierListReponse
   */
  error_url: string;
  /**
   *
   * @type {number}
   * @memberof UploadQualifierListReponse
   */
  amount: number;
}
