/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface UserTokenBalanceListItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UserTokenBalanceListItem {
  /**
   *
   * @type {number}
   * @memberof UserTokenBalanceListItem
   */
  token_id: number;
  /**
   *
   * @type {string}
   * @memberof UserTokenBalanceListItem
   */
  token_symbol: string;
  /**
   *
   * @type {string}
   * @memberof UserTokenBalanceListItem
   */
  token_icon: string;
  /**
   *
   * @type {string}
   * @memberof UserTokenBalanceListItem
   */
  chain: string;
  /**
   *
   * @type {string}
   * @memberof UserTokenBalanceListItem
   */
  total_balance: string;
  /**
   *
   * @type {string}
   * @memberof UserTokenBalanceListItem
   */
  avail_balance: string;
  /**
   *
   * @type {string}
   * @memberof UserTokenBalanceListItem
   */
  lock_balance: string;
  /**
   *
   * @type {string}
   * @memberof UserTokenBalanceListItem
   */
  chain_label: string;
  /**
   *
   * @type {string}
   * @memberof UserTokenBalanceListItem
   */
  chain_icon: string;
}
