/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { NftType } from "./nft-type";

/**
 *
 * @export
 * @interface UserNftBalanceListItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UserNftBalanceListItem {
  /**
   *
   * @type {string}
   * @memberof UserNftBalanceListItem
   */
  chain: string;
  /**
   *
   * @type {string}
   * @memberof UserNftBalanceListItem
   */
  nft_address: string;
  /**
   *
   * @type {NftType}
   * @memberof UserNftBalanceListItem
   */
  nft_type: NftType;
  /**
   *
   * @type {number}
   * @memberof UserNftBalanceListItem
   */
  collection_id: number;
  /**
   *
   * @type {string}
   * @memberof UserNftBalanceListItem
   */
  collection_name: string;
  /**
   *
   * @type {number}
   * @memberof UserNftBalanceListItem
   */
  total_balance: number;
  /**
   *
   * @type {number}
   * @memberof UserNftBalanceListItem
   */
  avail_balance: number;
  /**
   *
   * @type {number}
   * @memberof UserNftBalanceListItem
   */
  lock_balance: number;
}
