/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { UserCampaignStatus } from "./user-campaign-status";
import { UserEligibleStatus } from "./user-eligible-status";
import { UserRewardListItem } from "./user-reward-list-item";
import { UserTaskStatus } from "./user-task-status";

/**
 * 用户活动状态信息
 * @export
 * @interface UserCampaignStatusInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UserCampaignStatusInfo {
  /**
   *
   * @type {UserCampaignStatus}
   * @memberof UserCampaignStatusInfo
   */
  user_status: UserCampaignStatus;
  /**
   *
   * @type {Array<UserTaskStatus>}
   * @memberof UserCampaignStatusInfo
   */
  task_status_details: Array<UserTaskStatus>;
  /**
   *
   * @type {UserEligibleStatus}
   * @memberof UserCampaignStatusInfo
   */
  campaign_eligible: UserEligibleStatus;
  /**
   *
   * @type {Array<boolean>}
   * @memberof UserCampaignStatusInfo
   */
  campaign_eligible_details: Array<boolean>;
  /**
   *
   * @type {Array<UserRewardListItem>}
   * @memberof UserCampaignStatusInfo
   */
  qualifier_rewards: Array<UserRewardListItem>;
  /**
   *
   * @type {Array<UserRewardListItem>}
   * @memberof UserCampaignStatusInfo
   */
  winner_rewards: Array<UserRewardListItem>;
}
