/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { UserNftBalanceListItem } from "./user-nft-balance-list-item";

/**
 *
 * @export
 * @interface UserNftBalanceList
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UserNftBalanceList {
  /**
   *
   * @type {Array<UserNftBalanceListItem>}
   * @memberof UserNftBalanceList
   */
  data: Array<UserNftBalanceListItem>;
  /**
   *
   * @type {number}
   * @memberof UserNftBalanceList
   */
  total: number;
}
