/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface UserCampaignStatus
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UserCampaignStatus {
  /**
   *
   * @type {boolean}
   * @memberof UserCampaignStatus
   */
  is_visitor: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserCampaignStatus
   */
  is_participant: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserCampaignStatus
   */
  is_submitter: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserCampaignStatus
   */
  is_qualifier: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserCampaignStatus
   */
  is_winner: boolean;
}
