/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { BUserStatus } from "./buser-status";
import { Domain } from "./domain";
import { SnsItem } from "./sns-item";
import { UserInfoAddress } from "./user-info-address";
import { UserRole } from "./user-role";

/**
 * UserInfo用户信息
 * @export
 * @interface UserInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UserInfo {
  /**
   *
   * @type {number}
   * @memberof UserInfo
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  avatar: string;
  /**
   *
   * @type {number}
   * @memberof UserInfo
   */
  exp: number;
  /**
   *
   * @type {number}
   * @memberof UserInfo
   */
  level: number;
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  user_name: string;
  /**
   * 用户绑定的sns账户
   * @type {Array<SnsItem>}
   * @memberof UserInfo
   */
  sns: Array<SnsItem>;
  /**
   *
   * @type {BUserStatus}
   * @memberof UserInfo
   */
  b_user: BUserStatus;
  /**
   * 用户绑定的钱包地址
   * @type {Array<UserInfoAddress>}
   * @memberof UserInfo
   */
  address: Array<UserInfoAddress>;
  /**
   *
   * @type {Array<UserRole>}
   * @memberof UserInfo
   */
  roles?: Array<UserRole>;
  /**
   *
   * @type {Domain}
   * @memberof UserInfo
   */
  domains?: Domain;
}
