/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { RewardExpValue } from "./reward-exp-value";
import { RewardNftValue } from "./reward-nft-value";
import { RewardTokenValue } from "./reward-token-value";
import { RewardType } from "./reward-type";

/**
 *
 * @export
 * @interface UserRewardListItem
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface UserRewardListItem {
  /**
   *
   * @type {RewardType}
   * @memberof UserRewardListItem
   */
  reward_type: RewardType;
  /**
   *
   * @type {RewardTokenValue | string | RewardExpValue | RewardNftValue}
   * @memberof UserRewardListItem
   */
  reward_value: RewardTokenValue | string | RewardExpValue | RewardNftValue;
  /**
   *
   * @type {number}
   * @memberof UserRewardListItem
   */
  receive_time: number;
}
