/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

import { CampaignStatus } from "./campaign-status";
import { RewardType } from "./reward-type";
import { UserCampaignStatusOptions } from "./user-campaign-status-options";
import { UserEligibleStatus } from "./user-eligible-status";

/**
 *
 * @export
 * @interface V1GetCampaignListOptions
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface V1GetCampaignListOptions {
  /**
   * 按活动名字模糊搜索
   * @type {string}
   * @memberof V1GetCampaignListOptions
   */
  name_like?: string;
  /**
   *
   * @type {CampaignStatus}
   * @memberof V1GetCampaignListOptions
   */
  campaign_status?: CampaignStatus;
  /**
   *
   * @type {UserCampaignStatusOptions}
   * @memberof V1GetCampaignListOptions
   */
  user_campaign_status?: UserCampaignStatusOptions;
  /**
   * 是否按用户joined 活动过滤
   * @type {boolean}
   * @memberof V1GetCampaignListOptions
   */
  user_joined?: boolean;
  /**
   * 是否按用户created活动过滤
   * @type {boolean}
   * @memberof V1GetCampaignListOptions
   */
  user_created?: boolean;
  /**
   * 是否返回首页置顶活动
   * @type {boolean}
   * @memberof V1GetCampaignListOptions
   */
  top_campaigns?: boolean;
  /**
   *
   * @type {UserEligibleStatus}
   * @memberof V1GetCampaignListOptions
   */
  user_eligible_status?: UserEligibleStatus;
  /**
   *
   * @type {RewardType}
   * @memberof V1GetCampaignListOptions
   */
  reward_type?: RewardType;
  /**
   * 是否是nft类型且已经claim成功
   * @type {boolean}
   * @memberof V1GetCampaignListOptions
   */
  nft_claimed?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof V1GetCampaignListOptions
   */
  is_owner_verified: boolean;
}
