/**
 * TaskOn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 *
 * @export
 * @interface WinnerInfo
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
export interface WinnerInfo {
  /**
   * 用户id
   * @type {number}
   * @memberof WinnerInfo
   */
  user_id: number;
  /**
   * 用户地址
   * @type {string}
   * @memberof WinnerInfo
   */
  user_address: string;
  /**
   *
   * @type {string}
   * @memberof WinnerInfo
   */
  user_name: string;
  /**
   * 头像
   * @type {string}
   * @memberof WinnerInfo
   */
  avatar: string;
  /**
   * token 金额
   * @type {string}
   * @memberof WinnerInfo
   */
  amount?: string;
}
